apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: lome-dev-deployment
  name: lome-dev-deployment
  namespace: lome-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lome-dev-deployment
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: lome-dev-deployment
    spec:
      containers:
        - image: ghcr.io/h1ghbre4k3r/lome-dev:f2fb559091b2b6f3b5f983c9ddc7d90d5759ca1b
          imagePullPolicy: Always
          name: lome-dev-deployment
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
